### PR TITLE
resolved compiler warnings

### PR DESCRIPTION
**Pull request by Ownasaurus**
When I downloaded the code and tried to compile it, I was met with a sea of compiler warnings. I handled them in two ways:

1. I resolved the warnings which were easily resolvable, including type warnings and unsafe/depreciated function usage.
2. For warnings that were present throughout and would require a large overhaul to fix, I suppressed those warnings using #pragma commands

Please note that these changes are **UNTESTED** since I have never used D2BS before. I would ideally like somebody to test the .dll to confirm it is functional, and if so, to accept the changes.

### CODE REVIEW

**Comment by noah-** [comment]
Can you fix the formatting

**Comment by Ownasaurus** [comment]
Sure. I believe the formatting issues have been resolved.

**Comment by Ownasaurus** [comment]
This pull request now no longer contains any static casts. This has re-introduced 9 warnings. Still, much better off than it was originally.

It still has great changes for disabling undesired warnings, using safer function calls, commenting out unused variables, resolving certain signed/unsigned conflicts, and re-working some un-reachable code regions.

**Comment by Ownasaurus** [comment]
had to rebase so closing PR

**Pull request closed without merging**
